### ISSUE TITLE
Fehler in der Berechnuntg

### ISSUE THREAD

**Issue by Manfred-Gipp** [agonyz/contao-countdown-bundle#2]
Wenn ich die Sekunden ausblenden möchte, bleiben die Sekunden und es wird komplett falsch berechnet.
Zeige ich alles an und habe mehr als 80 Tage, dann werden die Tage gekürzt. Bei mir sollten 1580 Tage angezeigt werden, aber es werden nur 80 Tage angezeigt.

**Comment by agonyz** [comment]
Hallo @Manfred-Gipp, danke für den Hinweis. Ist bereits eine etwas ältere Erweiterung, welche ich gar nicht mehr auf dem Schirm hatte.

Sollte nun in der Version `0.2.1` gefixt sein.
Gerne kurze Rückmeldung, ob das die Probleme behoben hat.

**Comment by gww-its** [comment]
Super. Beide Fehler sind jetzt nicht mehr da. Herzlichen Dank. Ich fand diese Erweiterung für mich als kleiner Scherz auf meiner eigenen Seite eine ganz gute Idee. Deswegen habe ich die verwendet. Dabei bin ich auf die beiden Fehler gestoßen. https://gipp-weltweit.de

**Comment by agonyz** [comment]
Freut mich und immer gerne.
Coole Idee mit dem Scherz auf deiner Seite. Gefällt mir! :D
